### PR TITLE
QPIDJMS-374: Use getRawQuery to avoid double encoding

### PR DESCRIPTION
**Pull request by mibo**

### CODE REVIEW

**Comment by tabish121** [comment]
I believe the correct fix is to call PropertyUtil.parseQuery(remoteURI) instead and it will do the right thing, although we can't know until you provide some tests to validate it.

**Comment by mibo** [comment]
I agree that using `PropertyUtil.parseQuery(remoteURI)` would be better (which then does the `PropertyUtil.parseQuery(uri.getRawQuery())` call after a [null check](https://github.com/apache/qpid-jms/blob/70fe1b882e1381b1016a10b0707f6e112d4e0598/qpid-jms-client/src/main/java/org/apache/qpid/jms/util/PropertyUtil.java#L189)).
I will change it and add the currently missing (JUnit) tests.
But I think we can agree that using `PropertyUtil.parseQuery(remoteURI.getQuery())` is a bug.

Btw. I oriented the fix by the [TransportFactory](https://github.com/apache/qpid-jms/blob/70fe1b882e1381b1016a10b0707f6e112d4e0598/qpid-jms-client/src/main/java/org/apache/qpid/jms/transports/TransportFactory.java#L51).

**Comment by mibo** [comment]
Changed to use `PropertyUtil.parseQuery(remoteURI)` and added tests.

**Comment by tabish121** [comment]
You need to squash the commits and force push so that it is contained in one commit, thanks.

**Pull request merged**
