### PR TITLE
QPIDJMS-441: add proxy support

### PR DESCRIPTION
**Pull request by stsiano**
This is an intial version of proxy support for the qpid-jms libary. The implementation as such is rather trivial (the actual coding that is really doing something is the change in NettyTcpTransport, the rest is just for moving the ProxyHandler from the JmsConnectionFactory (where it is configured) to NettyTcpTransport (where it is used).

Tests are still missing (I just did a manual test).

### CODE REVIEW

**Comment by gemmellr** [comment]
We wouldn't want the JMS layer APIs to be directly dependent on fixed Netty types if we were to add this. There is as general setExtension method on the factory to be used rather than adding setters for each, the cases that do have one simply pre-dated the mechanism being added and were just reimplemented over it to leverage and exercise it. Ideally we also wouldn't have the proxy deps be required all the time either, but rather only needed if used, when the application would need to have/provide them anyway. I've made some example changes to that effect here: https://github.com/gemmellr/qpid-jms/tree/pr32-proxy

We would need tests as you've mentioned, in order for the changes to be accepted. In that area, I'd wonder if interaction with SSL/TLS peers beyond a proxy would be currently be handled. To your question on the JIRA, I don't have any dependencies to suggest as this isnt an area I've ever looked at before, but essentially the main requirement is they be permissively licensed, and preferably relatively light weight. Peeking at some other projects using Netty, and indeed Netty itself, suggests many just use their own test HTTP and SOCKS proxies.

**Comment by stsiano** [comment]
Your approach is of course also fine, but it makes using the interface a bit awkward. Furthermore the proxy is not optional with your implementation as you have a NettyTcpTransport class still depends on the ProxyHandler class (however you could use a ChannelHandler or a ChannelOutboundHandler instead (the ProxyHandler implements these interfaces)). Shall I update my change accordingly?

TLS/SSL works over a proxy.

I will start working on the tests when I find the time.

**Comment by gemmellr** [comment]
The ProxyHandler class is not required at runtime with what I did, unless you are using the extension, in which you you need to provide it. I left it using that type given its what's expected in that transport for that extension, rather than just any old handler.

**Comment by stsiano** [comment]
OK, I have provided a (very incomplete) HTTP proxy implementation that only implements the CONNECT request (which is used by the websocket transport) and configured a HttpProxyHandler for a new websocket connect test.

I have configured a fixed port for the proxy. Is there a way to get an arbitrary free port for a server socket?

**Comment by gemmellr** [comment]
The transport test is useful but more tests are definitely needed to ensure operation and that things dont get broken later. There arent any tests that actually exercise a connection being set up and configured the way an application would use it, so the connection process through the proxy isnt exercised, and the extension mechanism for passing through the handler from the factory is also untested. I believe currently the full-connection style tests are in the activem tests module for WS connections, everything else is in the client module (e.g ConnectionIntegrationTest, SslIntegrationTest). There also needs to be some SSL testing. The various create and clone etc tests in TransportOptionsTest need updated for the options change. A test doing failover would be needed to verify that works (I'd guess in that case it may additionally be necessary to require return of a new handler instance each time the handler Supplier get method is called, if so then that should perhaps be stated in the extension javadoc since Supplier itself notes it isnt a general requirement). If the extension mechanism is allowing for Socks proxy handlers to be passed then there should be tests for that too.

The changes altered the opentracing-util dependency from provided to compile scope, that should be put back as it was.

**Comment by stsiano** [comment]
OK, I have added a rudimentary Socks5 proxy implementation and added methods using the proxy in the NettyTcpTransportTest and the NettySslTransportTest (the NettyWssTransportTest extends the latter and therefore inherits the new methods).

Furthermore I extended the ConnectionIntegrationTest, the MessageIntegrationTest, the SslIntegrationTest and the FailoverIntegrationTest by classes that include the connection over a proxy (for this purpose I had to refactor the original tests slightly in order to make them extendable).

**Comment by tabish121** [comment]
I'm not sure I agree with the testing methodology of just picking a few random tests and duplicating the entire test case.  It adds a bunch of time to the unit test run(a full minute on my machine) but I'm not sure it actually narrowly targets the changes that have been made in a manner that actually proves the changes are sound for the various bits that really matter like failover which should be testing that new proxy handlers are swapped in for different URIs etc.  Also it doesn't seem to hit cases of the proxy itself being down or malfunctioning.  I saw that Netty has a suite of tests that can simulate different error failures of the proxy itself which might be a good thing to emulate.  

I'd rather see something like a ProxiedConnectionTest that covers the aspects of using the proxy where things go wrong and we ensure that they are handled.  Otherwise just running some already written tests with the proxy thrown in doesn't really test the edges.

**Comment by stsiano** [comment]
If you look into the actual productive coding in the pull request, you will see that it actually doesn't contain any code changes that can go wrong locally. The code actually allows you to set a ProxyHandler in an extension of the JmsConnectionFactory. If you do so, it will prevent name resolution within the library and set the proxy handler to the Netty Channel used for the communication with the broker.

All the real coding for communicating over the proxy is in Netty (and therefore tested there). In the end there is not so much magic in the proxies, Netty will handshake with the proxy and then the proxy will forward the socket to the actual target system, the rest of the communication with the message broker is actually handled over this forwarded socket. (This is a bit simplified, the Socks5 and HTTP proxies also allow other kinds of connectivity, but qpid-jms will not use them). If the proxy is unavailable or causing errors you will have the same situation as if the network infrastructure would be broken or unavailable. I could add a test that tests that the connectivity fails if a proxy is configured but does not exist (which is essentially the same as if it is down).

Robbie Gemmell wanted some integration tests in particular for Connect, TLS, and failover. In particular the failover test is a bit problematic because it contains errors and timeouts and my simple test proxy implementations might influence error handling and timing behavior. In the TravisCI build it succeeded with OpenJDK 8 and 11, but failed with the XCode 9.3 build (on my local PC it also works, so it's a bit hard to find out why it fails in this particular CI build).

I could live well with only one of these integration tests (e.g. the MessageIntegrationTest to show that proxy configuration and message processing works over a proxy).

@gemmellr What do you think how many integration tests should be there.

**Comment by gemmellr** [comment]
I also disagree with the way the tests are in the latest commit, it isnt what I was thinking of previously at all and largely needs unwound I think. I am not looking for a complete duplication of entire tests for largely unrelated functional areas such as most of the connection and message processing and failover tests. Definitely not looking to add a minute to the test suite, even seconds is pushing it for this I think.

I simply wanted to see at least a handful of tests actually exercising the overall functionality in basic but key situations, e.g establishing an actual connection to ensure connection creation works at all (seems like still none in this area for the HTTP case?), plus doing SSL/TLS at all, checking that it works with failover at all (e.g also verifying the handler supplier is used at each reconnect), and implicitly through all of these that the factory extension mechanism for providing the handlers actually gets exercised. That there were originally no tests covering any of these meant that the overall functionality could easily have been broken from the start or in future without any indication. I think Tim's idea of grouping many/most of the tests for this in a specific class would likely be good. TransportOptionsTest also still needs updated to reflect the changes made to the options.

While many of the underlying smarts here are in Netty and those bits are indeed tested in Netty as you say, there needs to be client tests to ensure that we actually use those bits correctly, that it all works together as expected now, and that the overall functionality continues to work in the face of future change in both the client itself and Netty.

**Comment by stsiano** [comment]
In general the functionality with proxy should be the same that it is without. Is it possible to just tell me precisely which test cases (classes/methods) you want to have duplicated with proxy and which additional checks you want on that test for the proxy? I am pretty sure that you know what you think to be the basic but key situations, but it's pretty hard for me who doesn't know the code base as a whole in every details what you think these basic situations are.

Please also understand my situation: There are about three thousand tests alone in the qpid-jms-client project. It takes me some time to understand what a specific test does and how it works, so I will have a very hard time to find a handful of relevant tests among them. If I start writing new tests from scratch without understanding your overall test concept and aligning with your general test strategy, methodology, and naming conventions the tests will be very hard to maintain (because they work entirely different from what you already have).

**Comment by gemmellr** [comment]
I understand a lot of its the same, thats why we are not expecting to see swathes of tests duplicated but rather simple test coverage only for the new functionality being added with its own specific wiring needing exercised.

As I've noted for me basic and key situations would be exercising creating an actual connection over the proxy, then again with SSL/TLS, for each proxy type, plus verifying the proxying stuff works at all with failover connections and e.g that the supplier gets called for each connect+reconnect.

I don't think anyone is expecting you to know all of the codebase or inspect all 3000 the tests, that's why we've touched on specific classes and locations etc until now. I have not had a specific set of tests in mind to duplicate because I've not been looking to simply do that. Obviously I'd expect you to draw from some of the existing tests though, many of which were already specifically touched on or you've modified already. A lot of these are not mysterious, e.g, look at the names or even the first test in many cases, or grep for the URL scheme.

For example, ConnectionIntegrationTest.testCreateAndCloseConnection() creates and closes a connection. Something similar to that, which connected through a Socks proxy, gives us some indication that there is proxy handling functionality occurring and helps ensure it continues to. Similarly with SSL/TLS, e.g see SslIntegrationTest.testCreateAndCloseSslConnectionJDK(). For failover, essentially any test that actually performs a failover would likely provide appropriate inspiration, e.g FailoverIntegrationTest.testCreateConsumerAfterConnectionDrops(). A variant of that using a proxy helps assure it works with failover, and e.g could also verify how many times the handler supplier is used. For Websockets and HTTP proxy, you could give JmsWSConnectionTest and JmsWSSConnectionTest a look in the activemq tests module. Obviously that being its own module would mean either moving the proxy there and forgoing the transport test, or duplicating the proxy, personally I'd be fine with either of those approaches personally. Finally, updating the existing TransportOptionsTest tests to cover the new options field added to the TransportOptions class.

**Comment by stsiano** [comment]
I have created another version of the pull request. Here the test proxy implementation is duplicated (in qpid-jms-client and qpid-jms-activemq-tests). Maybe it would be better to move this to a separate module (e.g. qpid-jms-tests-helper) and import that as a test dependency in both modules (the proxy code has slf4j-api as its only dependency). Aside from that I would consider this closer to completion now.

I also found something that does not work: amqp+wss does not work with a HTTP proxy (it works with a Socks Proxy). This is actually an unresolved Netty issue: https://github.com/netty/netty/issues/5201 

The HTTP proxy handler adds another HttpClientCodec at the beginning of the pipeline. (so there are actually two HttpClientCodecs in the pipeline. This confuses the WebSocketClientHandshaker to add the ws-encoder and ws-decoder at the wrong place in the pipeline. For some reason I don't really understand this still works without TLS, but a wss connection collapses after the web socket conversion.
This should work if the issue ever gets fixed in Netty, but right now I don't have a good solution to get this combination running. I also think that this feature is useful enough without this combination.

**Comment by stsiano** [comment]
I have found a workaround for the netty issue with the HTTP Proxy / wss combination: If we use a  HttpRequestEncoder/HttpResponseDecoder combination instead of the HttpClientCodec, we will have only one of each in the pipeline and the WebSocketClientHandshaker can add the WebSocketFrameEndcoder/Decoder at the right place and remove the HttpRequestEncoder/HttoRequestDecoder added by the NettyWsTransport instead of the HttpClientCodec created by the HttpProxyHandler.

I prepared that as a second commit (because this actually changes proxy unrelated coding)

**Comment by gemmellr** [comment]
As Tim and I suggested, a specific test class (e.g ProxyIntegrationTest) for the full-connection proxy tests would seem better (i.e not the options or transport tests). I don't think the connection related changes to IntegrationTestFixture and FailoverIntegration test are that desirable given the added methods aren't going to be used widely or at all in some cases. A util method for connecting within the new test class would do nicely for this.

Tim noted to me just now that he remembered there is a websocket-capable basic test server in the client module these days, which I had forgotten, so you should be able to use that and thus remove the tests and proxy copy from the activemq tests module. See NettySimpleAmqpServer(TransportOptions, boolean, boolean, boolean).

I noticed that the TestProxy assigns to its listenThread variable in a loop, meaning it overwrites as it goes and will only ever try joining one at close, plus these then spawn other threads it also cant join. Stepping back, I think it would make sense to simplify the proxy to only supporting a single connection, which would reduce its complexity and allow using one thread for more of the work, or perhaps even all of it (could use a read timeout via socket.setSoTimeout to allow servicing both sockets from the middle) which is what we do in the TestAmqpPeer. You would then just use 2 TestProxy instances for the failover test and verify both handle a connection, having the supplier return a handler for each proxy when asked (and throw if it is asked more times than expected), also allowing verifying how often the supplier is called as noted previously.

Its good that you found a workaround for the WS TLS issue as I actually think that is one of the more important cases, one of the reasons I pushed for such testing, and so I don't think we would have wanted to add it with that broken if there was possibility it could be resolved soon and included. At the very least we would probably have wanted to instead specifically reject such a config. The most recent activity around the netty issue (on PR 9564) currently suggests a resolution that wouldn't implicitly make it just work in future, but instead enable slightly different usage that could be done to then let it to work.

Please just squash the 2nd commit since its just one overall change, plus it will be more helpful later to see that the code was changed while/due-to adding the proxy functionality.

**Comment by stsiano** [comment]
I have moved the full connection proxy test cases into a separate class.

Furthermore I have reworked the TestProxy class to use nio, so there is no explicit thread handling anymore.

I also had a look into the NettySimpleAmqpServer class and its uses (NettyTcpToMockServerTest). I did not manage to create a test case with that, that succeded with the current code but failed with the HttpClientCodec in the NettyWsTransport class, so I kept the activemq tests for the ws connectivity.

**Comment by gemmellr** [comment]
Tim and I took a look at this latest version and made some fixes and tweaks, you can see the current state of them in the second commit at:
https://github.com/apache/qpid-jms/compare/master...gemmellr:pr32-proxy-b

There is still a remaining issue needing resolved before the addition can be made however. The failover test (\[1\]) failed very occasionally for me when run locally, and fails a lot of the time when run in the Appveyor CI job on Windows. After some digging we eventually established this seems to happen when the proxy doesnt look to close the connection from the client, after the test peer drops the server end. The client thus doesn't notice the drop as intended in the test, which eventually times out waiting for the failover and subsequent test steps to happen.

This seems to happen only when the proxy code goes through this segment: https://github.com/apache/qpid-jms/commit/436092b2eba9a4b46a7b5ed404e60e3803d0f141#diff-a85fa6452826ab6e749d0c34973365f1R310 of the read processing. However, just adding a matching close for the writeChannel there makes the test (and others) fail differently, doing the expected steps but throwing during autoclosure of the test peer because its final read attempt had thrown a connection reset exception. Its not immediately clear to me why that happens, but the test issues need resolved one way or another before this can be merged so it would be good if you could debug it to resolve it.

If you identify a fix, just add a new commit on top of those ones so we can easily see the new changes. You can enable Appveyor (https://ci.appveyor.com) on your fork of the repo and it will pick up the existing configuration in there and run when you push changes, plus you can repeat builds through the Appveyor site. The Repeat annotation (\[2\]) above the test can be be useful for running lots of iterations of a test in a single test run while verifying changes.

(\[1\]) https://github.com/apache/qpid-jms/commit/436092b2eba9a4b46a7b5ed404e60e3803d0f141#diff-eab37a02742dcdeacb54fd8fde6e5a6bR133
(\[2\]) https://github.com/apache/qpid-jms/commit/436092b2eba9a4b46a7b5ed404e60e3803d0f141#diff-eab37a02742dcdeacb54fd8fde6e5a6bR131

**Comment by stsiano** [comment]
I could unfortunately not reproduce the issue for me, the test always works for me (regardless how often I call it and to which value I set the Repeat annotation). When I tried to get the Appveyor running with my fork, I got some unspecified error (address to appveyor support).

Nevertheless it always felt wrong to ignore the write channel altogether on an EOF at the read channel. I think the correct reaction of that is to shutdown the output on the write channel if it exists and is still open. This way the reader at the forwarded socket will also get an EOF (as we did in the proxy), so the situation should be the same as without the proxy.

I have created another commit for that. The logs look very reasonable for me for the failover test, but as I said, I cannot reproduce your issue, so it would be good if you could give it a try.

**Comment by gemmellr** [comment]
I've put the tests through hundreds of iterations locally and more in CI with the latest change and they now seem stable now, so I've squashed and merged the changes. Thanks for the contribution.

**Pull request closed without merging**
